import time
import importlib
import streamlit as st
import yfinance as yf
import plotly.graph_objects as go
import pandas as pd

# Standard import for shareconf
from shareconf import fetch_market_data, export_pdf_report

# Using importlib to safely import the CIO agent file with the space
cio_module = importlib.import_module("CIO agent")
run_multi_agent_system = cio_module.run_multi_agent_system

# ==========================================
# PAGE SETUP
# ==========================================
st.set_page_config(page_title="Pro Investor System", layout="wide")

def main():
    st.title("🤖 Agentic AI-Driven Multi-Agent Framework for Simplified Stock Market Analysis")
    st.markdown("Analyze assets, compare performance, and generate AI-driven reports using a dynamically scaling multi-agent workflow.")

    with st.sidebar:
        st.header("Configuration")
        with st.form("input_form"):
            ticker_input = st.text_input("Enter Stocks (Comma Separated)", "AAPL, TSLA, GOOG")

            strategy_input = st.selectbox("Time Frame", ["6 Month", "3 Year"])

            with st.popover("ℹ️ How do these Timeframes work?"):
                st.markdown("""
                **Short Term + News Investment (Choose 6 Month):**
                News effects are highly influential but short-lived. Extensive market R&D and backtesting reveal that a 6-month timeframe is the optimal window to capture swing-trading momentum generated by immediate market catalysts before the trend fades. 
                
                **Long Term Investment (Choose 3 Year):**
                This is an intermediate-to-long-term holding timeframe. It provides ideal accuracy for evaluating a company's structural fundamentals (P/E, Max Drawdown). It filters out daily market noise without relying on data that is too outdated, offering a balanced, highly accurate view of sustainable growth.
                """)

            st.write("")
            trigger = st.form_submit_button("Run Multi-Agent Analysis", use_container_width=True)

    if trigger:
        tickers = [t.strip().upper() for t in ticker_input.split(",") if t.strip()]

        if not tickers:
            st.warning("Please enter at least one valid ticker symbol.")
            return

        processed_data = []

        selected_timeframe = "6mo" if strategy_input == "6 Month" else "3y"

        with st.spinner(f"Fetching {selected_timeframe} Market Data & Initializing Agents..."):
            for t in tickers:
                d = fetch_market_data(t, selected_timeframe)
                if d:
                    processed_data.append(d)

        if not processed_data:
            st.error("Could not retrieve data for any of the entered tickers.")
            return

        st.subheader("Performance Overview")
        cols = st.columns(len(processed_data))
        for i, entry in enumerate(processed_data):
            with cols[i]:
                st.metric(
                    label=f"{entry['symbol']}",
                    value=f"{entry['return']}%",
                    delta=f"Sharpe: {entry['sharpe']}",
                    delta_color="normal" if entry['sharpe'] > 0 else "inverse"
                )

        st.divider()

        st.markdown(f"### Key Statistics ({strategy_input})")
        df_display = pd.DataFrame(processed_data).drop(columns=['data'])
        df_display.rename(columns={
            "symbol": "Asset",
            "return": "Return (%)",
            "volatility": "Volatility (%)",
            "sharpe": "Sharpe Ratio",
            "max_drawdown": "Max Drawdown (%)",
            "pe": "P/E Ratio"
        }, inplace=True)
        df_display = df_display[["Asset", "Return (%)", "Volatility (%)", "Max Drawdown (%)", "Sharpe Ratio", "P/E Ratio"]]
        st.dataframe(df_display, hide_index=True, use_container_width=True)

        st.divider()

        st.markdown("### Price Action & 50-Day Moving Average")
        fig = go.Figure()

        for d in processed_data:
            df = d["data"]
            fig.add_trace(go.Scatter(x=df.index, y=df["Close"], mode='lines', name=f"{d['symbol']} Close", line=dict(width=2)))

            if len(df) >= 50:
                sma_50 = df["Close"].rolling(window=50).mean()
                fig.add_trace(go.Scatter(x=df.index, y=sma_50, mode='lines', name=f"{d['symbol']} 50d SMA", line=dict(width=1.5, dash='dot'), opacity=0.7))

        fig.update_layout(
            margin=dict(l=20, r=20, t=20, b=20),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            hovermode="x unified",
            plot_bgcolor='rgba(0,0,0,0)',
            yaxis_title="Stock Price (USD)"
        )
        st.plotly_chart(fig, use_container_width=True)
        st.divider()

        # ==========================================
        # NEWS FETCHING (Runs ONLY if 6 Month selected)
        # ==========================================
        news_summary_str = ""

        if strategy_input == "6 Month":
            st.subheader("📰 Market News Data")

            with st.spinner("Fetching latest news to feed the Sentiment Agent..."):
                news_data = {}
                for t in tickers:
                    try:
                        tkr_obj = yf.Ticker(t)
                        recent_news = tkr_obj.news[:4]
                        news_data[t] = recent_news
                    except Exception as e:
                        news_data[t] = []

                col1, col2 = st.columns([1, 1])
                col_idx = 0

                for t, news_list in news_data.items():
                    target_col = col1 if col_idx % 2 == 0 else col2
                    with target_col:
                        st.markdown(f"**{t} Recent Headlines:**")
                        if news_list:
                            for n in news_list:
                                if isinstance(n, dict):
                                    title = n.get('title') or n.get('content', {}).get('title', 'Headline Unavailable')
                                    link = n.get('link')
                                    if not link:
                                        content = n.get('content', {})
                                        can_url = content.get('canonicalUrl', {})
                                        link = can_url.get('url', '#') if isinstance(can_url, dict) else can_url or '#'
                                    st.markdown(f"- [{title}]({link})")
                                else:
                                    st.markdown("- *Headline format unreadable*")
                        else:
                            st.markdown("- *No recent news found.*")
                    col_idx += 1

                # Bundle the news to pass to the Multi-Agent System
                for t, news_list in news_data.items():
                    titles = []
                    for n in news_list:
                        if isinstance(n, dict):
                            extracted_title = n.get('title') or n.get('content', {}).get('title', '')
                            if extracted_title:
                                clean_title = extracted_title.replace('"', "'").replace('\n', ' ').strip()
                                titles.append(clean_title)
                    news_summary_str += f"Stock {t}: {'; '.join(titles)} | "

            st.divider()

        # ==========================================
        # MULTI-AGENT COMMITTEE DECISION
        # ==========================================
        st.subheader("Multi-Agent Committee Decision")
        progress_text = f"Executing {strategy_input} Strategy. Agents are autonomously analyzing data. Please wait."
        my_bar = st.progress(0, text=progress_text)

        for percent_complete in range(100):
            time.sleep(0.01)
            my_bar.progress(percent_complete + 1, text=progress_text)

        result = run_multi_agent_system(processed_data, news_summary_str, strategy_input)
        my_bar.empty()

        # --- Individual UI Expanders ---
        st.markdown("#### Individual Analyst Reports")
        with st.expander("Agent 1: Value Analyst"):
            st.info(result["value"])
        with st.expander("Agent 2: Risk Analyst"):
            st.warning(result["risk"])
        with st.expander("Agent 3: Momentum Analyst"):
            st.success(result["momentum"])

        if strategy_input == "6 Month":
            with st.expander("Agent 4: News Sentiment Analyst"):
                st.info(result["news"])

        # --- Programmatically compile all Agent findings into H3 Headings ---
        combined_report = f"### AGENT 1: VALUE ANALYST\n{result['value']}\n\n"
        combined_report += f"### AGENT 2: RISK ANALYST\n{result['risk']}\n\n"
        combined_report += f"### AGENT 3: MOMENTUM ANALYST\n{result['momentum']}\n\n"

        if strategy_input == "6 Month":
            combined_report += f"### AGENT 4: NEWS SENTIMENT ANALYST\n{result['news']}\n\n"

        combined_report += f"---\n\n{result['cio']}"

        st.markdown("#### Chief Investment Officer (Final Synthesis & Verdict)")
        with st.container(border=True):
            st.markdown(combined_report)

        # The PDF export includes the exact same combined report layout
        pdf_report = export_pdf_report(processed_data, combined_report)
        st.download_button(
            label="Download Comprehensive PDF Report",
            data=pdf_report,
            file_name=f"Multi_Agent_Report_{strategy_input.replace(' ', '_')}.pdf",
            mime="application/pdf",
            type="primary",
            use_container_width=True
        )

if __name__ == "__main__":
    main()